set rnu nu ai cin ts=4 sw=4 mouse=a showtabline=2
"gcc debug mode compiles significantly slower, so we use -O0 here
map <F7> <ESC>:w<CR>:!clear && g++ "%" -o "%<" -std=c++11 -Wall -Wextra -Wconversion -Wshadow -O0 -DLITE -fsanitize=address -fsanitize=undefined -g -D_GLIBCXX_DEBUG && echo success<CR>
map <F8> <ESC>:w<CR>:!clear && g++ "%" -o "%<" -std=c++11 -Wall -Wextra -Wconversion -Wshadow -O2 -DLITE -fsanitize=address -fsanitize=undefined -g && echo success<CR>
map <F9> <ESC>:w<CR>:!clear && g++ "%" -o "%<" -std=c++11 -Wall -Wextra -Wconversion -Wshadow -O2 -DLITE && echo success<CR>
map <F10> <ESC>:!./"%<"<CR>

colorscheme desert
